apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-helm-svc
  name: nginx-helm-svc
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.nginx.port }}
    targetPort: 80
  selector:
    app: nginx
  externalTrafficPolicy: Local
  type: LoadBalancer
