---
replicaCount: 2

global:
  env:
    NAME: "dev"
    VAULT_URI: "http://dev-vault.aws.foreseeresults.com:8200"
    K8S_INGRESS_LB: "dev.poc.xiao.us.to"
    DEFAULT_JAVA_OPT: "-Dspring.profiles.active=dev,aws -DKAFKA_ADDRESS=dev-kafka-cxsuite.foresee.com:9092 -DKAFKA_TRACE_LOGGING_TOPIC=dev-core-platform-logging -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=10101 -Dplatform-security-redis.hostName=auth-tokens-dev.lbpwvt.ng.0001.use1.cache.amazonaws.com -Dplatform-security-redis.port=6379 -Deureka.client.eurekaServerDNSName=dev.aws.foreseeresults.com -Deureka.client.healthcheck.enabled=true -DMETRICS_TOPIC=dev-core-platform-metrics -DHYSTRIX_STREAM_TOPIC=dev-core-platform-circuit-breaker -DPLATFORM_CONFIG_SERVER_URI=http://dev-config-server.foresee.com/platform-config-server -DHYSTRIX_STREAM_ZK_NODES=internal-dev-zookeeper1-1419869712.us-east-1.elb.amazonaws.com,internal-dev-zookeeper2-1289508936.us-east-1.elb.amazonaws.com,internal-dev-zookeeper3-403794177.us-east-1.elb.amazonaws.com -Dlogging.config=classpath:log4j2-aws.xml -Dspring.cloud.config.username=config-server-user -Dspring.cloud.config.password=secret -Deureka.instance.lease-renewal-interval-in-seconds=30 -Deureka.instance.lease-expiration-duration-in-seconds=90 -DAsyncLoggerConfig.RingBufferSize=1024 -Dspring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect"

# version has to be first element and space matters for version_replace.sh to work
app:
  settings-service:
    version: "snapshot-201007-155754-0921"
    java-opts: "-Deureka.environment=dev -DAPPLICATION_NAME=settings-service"
    secret:
      role: "NTEwYTJjZTctNDU1OC1lNDk2LTBiOTMtNWY5YzFlOGY4OTZm"
      secret: "NjhiOGMxYmItZTZhMC1hZWE2LWIyZTYtODcwNzgwMTY4YzY5"
  event-tracking-service:
    version: "snapshot-201008-004414-0264"
    java-opts: " -Dapp.env=dev"
    secret:
      role: "IA=="
      secret: "IA=="
    prefix-url: "/event-tracking-service"

