---
replicaCount: 1

app:
  settings-service:
    version: "snapshot-201007-155754-0921"
    java-opts: "-Dspring.profiles.active=dev,aws -Deureka.environment=dev -DAPPLICATION_NAME=settings-service"
    secret:
      role: "NTEwYTJjZTctNDU1OC1lNDk2LTBiOTMtNWY5YzFlOGY4OTZm"
      secret: "NjhiOGMxYmItZTZhMC1hZWE2LWIyZTYtODcwNzgwMTY4YzY5"
  event-tracking-service:
    version: "snapshot-201008-004414-0264"
    java-opts: "-Dspring.profiles.active=aws,dev -Dapp.env=dev"
    secret:
      role: "IA=="
      secret: "IA=="

global:
  env:
    NAME: "dev"
    VAULT_URI: "http://dev-vault.aws.foreseeresults.com:8200"
    K8S_INGRESS_LB: ""
    DEFAULT_JAVA_OPT: ""

